# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/natha/OneDrive/Desktop/MIT/F20/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/trngwave_rcm_rom/trngwave_rcm_rom.xci
# IP: The module: 'trngwave_rcm_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/natha/OneDrive/Desktop/MIT/F20/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/trngwave_rcm_rom/trngwave_rcm_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trngwave_rcm_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/natha/OneDrive/Desktop/MIT/F20/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/trngwave_rcm_rom/trngwave_rcm_rom.xci
# IP: The module: 'trngwave_rcm_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/natha/OneDrive/Desktop/MIT/F20/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/trngwave_rcm_rom/trngwave_rcm_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trngwave_rcm_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
