# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/6.111/nexys4_ddr_default.xdc

# IP: ip/trngwave_image_rom/trngwave_image_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trngwave_image_rom || ORIG_REF_NAME==trngwave_image_rom} -quiet] -quiet

# IP: ip/sinewave_rcm_rom/sinewave_rcm_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sinewave_rcm_rom || ORIG_REF_NAME==sinewave_rcm_rom} -quiet] -quiet

# IP: ip/sinewave_image_rom_1/sinewave_image_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sinewave_image_rom || ORIG_REF_NAME==sinewave_image_rom} -quiet] -quiet
