# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/My Drive/Coursework/MIT/Fall 2020/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/sinewave_image_rom/sinewave_image_rom.xci
# IP: The module: 'sinewave_image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/sinewave_image_rom/sinewave_image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sinewave_image_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/My Drive/Coursework/MIT/Fall 2020/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/sinewave_image_rom/sinewave_image_rom.xci
# IP: The module: 'sinewave_image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/FPGA-DAW/FPGA DAW/FPGA DAW.srcs/sources_1/ip/sinewave_image_rom/sinewave_image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sinewave_image_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
