# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz.xci
# IP: The module: 'clk_wiz_65mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65mhz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz.xci
# IP: The module: 'clk_wiz_65mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/Coursework/MIT/Fall 2020/6.111/Final Project/FPGA DAW/FPGA DAW.srcs/sources_1/ip/clk_wiz_65mhz/clk_wiz_65mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
